// reports/reportGenerator.js — Markdown report generator for DES Studio simulation reports

import { callLLMOnce } from '../llm/apiClient.js';
import {
  buildModelDescriptionPrompt,
  buildReportRecommendationsPrompt,
  parseReportRecommendations,
  buildGoalGaps,
} from '../llm/prompts.js';

// ── Helpers ───────────────────────────────────────────────────────────────────

function formatDate(iso) {
  try {
    const d = new Date(iso || Date.now());
    return d.toLocaleDateString('en-GB', { day: '2-digit', month: 'long', year: 'numeric' });
  } catch {
    return String(iso || '');
  }
}

function sanitizeFilename(name) {
  return String(name || 'report').replace(/[/\\:*?"<>|]/g, '-');
}

function finiteStr(value, decimals = 2) {
  const n = Number(value);
  if (!Number.isFinite(n)) return '—';
  return n.toFixed(decimals);
}

function mdTable(headers, rows) {
  if (!rows.length) return '_No data available._\n';
  const head = `| ${headers.join(' | ')} |`;
  const divider = `| ${headers.map(() => '---').join(' | ')} |`;
  const body = rows
    .map(r => `| ${r.map(c => String(c ?? '—').replace(/\|/g, '\\|')).join(' | ')} |`)
    .join('\n');
  return [head, divider, body].join('\n') + '\n';
}

function getSummary(results = {}) {
  return results.summary || results.results?.summary || {};
}

// ── Section builders ──────────────────────────────────────────────────────────

function buildCover(model, runMeta) {
  return [
    `# ${model.name || 'Simulation'} — Analysis Report`,
    '',
    `**Run:** ${runMeta.runLabel || runMeta.runId || 'Unknown'}  `,
    `**Date:** ${formatDate(runMeta.runTimestamp)}  `,
    `**Generated by:** DES Studio · Engine v${runMeta.engineVersion || '1.0'}`,
    '',
    '---',
    '',
  ].join('\n');
}

function buildExecutiveSummary(model, results, recommendations) {
  const summary = getSummary(results);
  const lines = [
    '## Executive Summary',
    '',
    `> ${model.description || `Discrete-event simulation of the ${model.name || 'system'}.`}`,
    '',
  ];

  const kpiRows = [
    ['Entities served',      finiteStr(summary.served, 0)],
    ['Average waiting time', finiteStr(summary.avgWait)],
    ['Average service time', finiteStr(summary.avgSvc)],
    ['Average sojourn time', finiteStr(summary.avgSojourn)],
    ['Average WIP',          finiteStr(summary.avgWIP)],
    ['Reneged',              finiteStr(summary.reneged, 0)],
  ].filter(r => r[1] !== '—');

  if (kpiRows.length) {
    lines.push('### Key Performance Indicators', '');
    lines.push(mdTable(['Metric', 'Value'], kpiRows));
  }

  const top = Array.isArray(recommendations) && recommendations.length
    ? (recommendations.find(r => r.priority === 1) || recommendations[0])
    : null;
  if (top?.headline) {
    lines.push('### Primary Recommendation', '');
    lines.push(`**${top.headline}**`, '');
    if (top.finding) lines.push(top.finding, '');
  }

  lines.push('---', '');
  return lines.join('\n');
}

function buildModelDescription(descriptionText) {
  return [
    '## Model Description',
    '',
    descriptionText || '_No model description available._',
    '',
    '---',
    '',
  ].join('\n');
}

function buildExperimentConfig(experimentConfig, runMeta) {
  const rows = [
    ['Run ID',           runMeta.runId || '—'],
    ['Run label',        runMeta.runLabel || '—'],
    ['Run date',         formatDate(runMeta.runTimestamp)],
    ['Engine version',   runMeta.engineVersion || '1.0'],
    ['PRN algorithm',    runMeta.prnAlgorithm || 'mulberry32'],
    ['Random seed',      String(runMeta.seed ?? '—')],
    ['Warm-up period',   String(experimentConfig.warmupPeriod ?? experimentConfig.warmup ?? 0)],
    ['Run duration',     String(experimentConfig.maxSimTime ?? experimentConfig.runDuration ?? '—')],
    ['Replications',     String(experimentConfig.replications ?? 1)],
    ['Termination mode', experimentConfig.terminationMode || 'time'],
  ];
  return [
    '## Experiment Configuration',
    '',
    mdTable(['Parameter', 'Value'], rows),
    '---',
    '',
  ].join('\n');
}

function buildResults(model, results) {
  const summary = getSummary(results);
  const lines = ['## Simulation Results', ''];

  lines.push('### Summary Statistics', '');
  const summaryRows = [
    ['Total entities created',   finiteStr(summary.total, 0)],
    ['Entities served',          finiteStr(summary.served, 0)],
    ['Entities reneged',         finiteStr(summary.reneged, 0)],
    ['Average waiting time',     finiteStr(summary.avgWait)],
    ['Average service time',     finiteStr(summary.avgSvc)],
    ['Average sojourn time',     finiteStr(summary.avgSojourn)],
    ['Maximum sojourn time',     finiteStr(summary.maxSojourn)],
    ["Average WIP (Little's L)", finiteStr(summary.avgWIP)],
  ].filter(r => r[1] !== '—');
  if (summary.totalCost != null) summaryRows.push(['Total cost', finiteStr(summary.totalCost)]);
  if (summary.costPerServed != null) summaryRows.push(['Cost per entity served', finiteStr(summary.costPerServed)]);
  lines.push(mdTable(['Metric', 'Value'], summaryRows));

  const waitDist = results.waitDist || {};
  const queueNames = Object.keys(waitDist);
  if (queueNames.length) {
    lines.push('### Queue Wait-Time Distribution', '');
    const rows = queueNames.map(q => {
      const w = waitDist[q] || {};
      return [q, finiteStr(w.n, 0), finiteStr(w.mean), finiteStr(w.p50), finiteStr(w.p90), finiteStr(w.p95), finiteStr(w.p99)];
    });
    lines.push(mdTable(['Queue', 'N', 'Mean wait', 'P50', 'P90', 'P95', 'P99'], rows));
  }

  const servers = (model.entityTypes || []).filter(e => e.role === 'server');
  if (servers.length) {
    const resourceStats = summary.perResource || summary.resourceUtilisation || {};
    lines.push('### Resource Utilisation _(end-of-run snapshot)_', '');
    const rows = servers.map(s => {
      const pr = typeof resourceStats === 'object' ? resourceStats[s.name] : null;
      const util = pr?.utilisation ?? summary.utilisation;
      const utilStr = Number.isFinite(Number(util)) ? `${(Number(util) * 100).toFixed(1)}%` : '—';
      return [s.name, String(s.count ?? '—'), utilStr, finiteStr(pr?.busyCount, 0), finiteStr(pr?.idleCount, 0)];
    });
    lines.push(mdTable(['Resource', 'Count', 'Utilisation', 'Busy', 'Idle'], rows));
  }

  const goalGaps = buildGoalGaps(model, results.aggregateStats || {});
  if (Array.isArray(goalGaps) && goalGaps.length) {
    lines.push('### Performance Goal Assessment', '');
    const rows = goalGaps.map(g => [
      g.label || g.metric,
      `${g.operator} ${g.target}`,
      g.current != null ? finiteStr(g.current) : '—',
      g.met ? '✅ MET' : '❌ MISSED',
      g.gap != null ? finiteStr(g.gap) : '—',
    ]);
    lines.push(mdTable(['Goal', 'Target', 'Current', 'Status', 'Gap'], rows));
  }

  const aggStats = results.aggregateStats || {};
  const ciKeys = Object.keys(aggStats).filter(k => aggStats[k]?.n >= 2);
  if (ciKeys.length) {
    lines.push('### Replication Confidence Intervals (95%)', '');
    const rows = ciKeys.map(k => {
      const s = aggStats[k];
      return [k, finiteStr(s.mean), finiteStr(s.lower), finiteStr(s.upper), String(s.n || '—')];
    });
    lines.push(mdTable(['Metric', 'Mean', 'CI Lower', 'CI Upper', 'N'], rows));
  }

  lines.push('---', '');
  return lines.join('\n');
}

function buildRecommendations(recommendations) {
  const lines = ['## Recommendations', ''];

  if (!Array.isArray(recommendations) || !recommendations.length) {
    lines.push('_No recommendations could be generated for this run._', '', '---', '');
    return lines.join('\n');
  }

  recommendations.forEach((rec, idx) => {
    lines.push(`### ${rec.priority || idx + 1}. ${rec.headline || `Recommendation ${idx + 1}`}`, '');
    if (rec.confidence) lines.push(`**Confidence:** ${rec.confidence}  `);
    if (rec.finding) lines.push(`**Finding:** ${rec.finding}  `);
    if (rec.action) lines.push(`**Recommended Action:** ${rec.action}  `);
    if (rec.expectedImpact) lines.push(`**Expected Impact:** ${rec.expectedImpact}  `);
    lines.push('');
  });

  lines.push('---', '');
  return lines.join('\n');
}

function buildAppendix(model) {
  const lines = ['## Appendix — Model Specification', ''];

  const entityTypes = model.entityTypes || [];
  if (entityTypes.length) {
    lines.push('### Entity Types', '');
    lines.push(mdTable(
      ['Name', 'Role', 'Count'],
      entityTypes.map(e => [e.name || '—', e.role || '—', e.role === 'server' ? String(e.count ?? '—') : '—'])
    ));
  }

  const queues = model.queues || [];
  if (queues.length) {
    lines.push('### Queues', '');
    lines.push(mdTable(
      ['Name', 'Discipline', 'Capacity', 'Entity type'],
      queues.map(q => [q.name || '—', q.discipline || 'FIFO', q.capacity != null ? String(q.capacity) : '∞', q.customerType || '—'])
    ));
  }

  const bEvents = model.bEvents || [];
  if (bEvents.length) {
    lines.push('### Bound Events (B-Events)', '');
    lines.push(mdTable(
      ['Name', 'Effect (summary)'],
      bEvents.map(ev => [
        ev.name || ev.id || '—',
        (Array.isArray(ev.effect) ? ev.effect.join('; ') : String(ev.effect || '—')).substring(0, 120),
      ])
    ));
  }

  const cEvents = model.cEvents || [];
  if (cEvents.length) {
    lines.push('### Conditional Events (C-Events)', '');
    lines.push(mdTable(
      ['Name', 'Priority', 'Effect (summary)'],
      cEvents.map(ev => [
        ev.name || ev.id || '—',
        String(ev.priority ?? 1),
        (Array.isArray(ev.effect) ? ev.effect.join('; ') : String(ev.effect || '—')).substring(0, 120),
      ])
    ));
  }

  const stateVars = (model.stateVariables || []).filter(v => v.name);
  if (stateVars.length) {
    lines.push('### State Variables', '');
    lines.push(mdTable(
      ['Name', 'Initial value'],
      stateVars.map(v => [v.name, String(v.initialValue ?? '0')])
    ));
  }

  return lines.join('\n');
}

// ── Main export ───────────────────────────────────────────────────────────────

export async function generateReport(model = {}, results = {}, experimentConfig = {}, runMeta = {}) {
  let modelDescription = model.description || '';
  let recommendations = [];

  const [descResult, recsResult] = await Promise.allSettled([
    callLLMOnce(buildModelDescriptionPrompt(model)).catch(() => model.description || ''),
    callLLMOnce(buildReportRecommendationsPrompt(model, results)).catch(() => '[]'),
  ]);

  if (descResult.status === 'fulfilled') modelDescription = descResult.value || model.description || '';
  if (recsResult.status === 'fulfilled') recommendations = parseReportRecommendations(recsResult.value);

  return [
    buildCover(model, runMeta),
    buildExecutiveSummary(model, results, recommendations),
    buildModelDescription(modelDescription),
    buildExperimentConfig(experimentConfig, runMeta),
    buildResults(model, results),
    buildRecommendations(recommendations),
    buildAppendix(model),
  ].join('\n');
}

export { sanitizeFilename, formatDate };
